### ISSUE TITLE
Feature request: Making it possible to change the login password

### ISSUE THREAD

**Issue by Alirezanain** [adrianofoschi/konio-mobile#13]
Making it possible to change the login password

**Comment by Craggy73** [comment]
v1.1.0 has added this in settings, but is asking for seed phrase rather than current password, which would make more sense if you're already logged in the app.

Descriptions for reset password are stuck in Italian.

**Comment by adrianofoschi** [comment]
done.
Change password from settings
Reset password from unlock screen
