### ISSUE TITLE
Feature request: Include note/memo when sending coin

### ISSUE THREAD

**Issue by Craggy73** [adrianofoschi/konio-mobile#15]
On the send page. Allow for a short note/memo to be added with the send transaction. This is shown with your list of 'withdraw' activities.

Change 'withdraw' to 'sent' to match the Send button.

**Comment by adrianofoschi** [comment]
ok for short memo.
the withdraw is the action type, maybe we can translate it to "send" not "sent" becouse it could be fail.

**Comment by adrianofoschi** [comment]
all requests done.
